### ISSUE TITLE
Introduce the concept of workspace layouts

### ISSUE THREAD

**Issue by trevorsenior** [trevorsenior/tronwm#2]
Currently the workspace is styled using fixed CSS:

```css
        #workspace {
            position: fixed; left: 0; top:50px; right: 0; bottom: 0;
            display: flex;
            flex-direction: 'row';
            justify-content: 'flex-start';
            align-items: 'stretch';
            align-content: 'stretch';
            background-color: blue;
        }
```

This only allows windows to open in columns next to each other with fixed widths.

We want to add the following layouts (for now, to keep it simple)

  - columns
  - rows
